Config = Config or {}

Config.UsingDefaultQBApartments = true
Config.OnlyShowOnDuty = true
Config.UseCQCMugshot = true

-- Front, Back Side. Use 4 for both sides, we recommend leaving at 1 for default.
Config.MugPhotos = 1

-- Images for mug shots will be uploaded here. Add a Discord webhook. 
Config.Webhook = 'https://discord.com/api/webhooks/1101782484947042394/ctZSMIUpYpvqBL5fZHG0BcoE235Ykd1eVxO7Nw8DBmJ4JGWIPQWiLx91CczLAio0eEtY'

-- Clock-in notifications for duty. Add a Discord webhook.
-- Command /mdtleaderboard, will display top players per clock-in hours.
Config.ClockinWebhook = ''

-- If set to true = Fine gets automatically removed from bank automatically charging the player.
-- If set to false = The fine gets sent as an Invoice to their phone and it us to the player to pay for it, can remain unpaid and ignored.
Config.BillVariation = true

-- Set up your inventory to automatically retrieve images when a weapon is registered at a weapon shop or self-registered.
-- If you're utilizing lj-inventory's latest version from GitHub, no further modifications are necessary. 
-- However, if you're using a different inventory system, please refer to the "Inventory Edit | Automatic Add Weapons with images" section in ps-mdt's README.
Config.InventoryForWeaponsImages = "qb-inventory"

-- "LegacyFuel", "lj-fuel", "ps-fuel"
Config.Fuel = "LegacyFuel"

-- Google Docs Link
Config.sopLink = {
    ['police'] = '',
    ['ambulance'] = '',
    ['bcso'] = '',
    ['doj'] = '',
    ['sast'] = '',
    ['sasp'] = '',
    ['doc'] = '',
    ['lssd'] = '',
    ['sapr'] = '',
}

-- Google Docs Link
Config.RosterLink = {
    ['police'] = '',
    ['ambulance'] = '',
    ['bcso'] = '',
    ['doj'] = '',
    ['sast'] = '',
    ['sasp'] = '',
    ['doc'] = '',
    ['lssd'] = '',
    ['sapr'] = '',	
}

Config.PoliceJobs = {
    ['police'] = true,
    ['lspd'] = false,
    ['bcso'] = false,
    ['sast'] = false,
    ['sasp'] = false,
    ['doc'] = false,
    ['lssd'] = false,
    ['sapr'] = false,
    ['pa'] = false
}

Config.AmbulanceJobs = {
    ['ambulance'] = true,
    ['doctor'] = true
}

Config.DojJobs = {
    ['lawyer'] = true,
    ['judge'] = true
}

-- This is a workaround solution because the qb-menu present in qb-policejob fills in an impound location and sends it to the event. 
-- If the impound locations are modified in qb-policejob, the changes must also be implemented here to ensure consistency.

Config.ImpoundLocations = {
    [1] = vector4(436.68, -1007.42, 27.32, 180.0),
    [2] = vector4(-436.14, 5982.63, 31.34, 136.0),
}

-- Support for Wraith ARS 2X. 

Config.UseWolfknightRadar = false
Config.WolfknightNotifyTime = 5000 -- How long the notification displays for in milliseconds (30000 = 30 seconds)

-- IMPORTANT: To avoid making excessive database queries, modify this config to true 'CONFIG.use_sonorancad = true' setting in the configuration file located at 'wk_wars2x/config.lua'. 
-- Enabling this setting will limit plate checks to only those vehicles that have been used by a player.

Config.LogPerms = {
	['ambulance'] = {
		[4] = true,
	},
	['police'] = {
		[4] = true,
	},
    ['bcso'] = {
		[4] = false,
	},
    ['sast'] = {
		[4] = false,
	},
    ['sasp'] = {
		[4] = false,
	},
    ['sapr'] = {
		[4] = false,
	},
    ['doc'] = {
		[4] = false,
	},
    ['lssd'] = {
		[4] = false,
	},
}

Config.PenalCodeTitles = {
    [1] = 'OVERTREDINGEN TEGEN PERSONEN',
    [2] = 'OVERTREDINGEN MET DIEFSTAL',
    [3] = 'OVERTREDINGEN MET BETREKKING TOT FRAUDE',
    [4] = 'OVERTREDINGEN MET SCHADE AAN EIGENDOMMEN',
    [5] = 'OVERTREDINGEN TEGEN OPENBARE ADMINISTRATIE',
    [6] = 'OVERTREDINGEN TEGEN DE OPENBARE ORDE',
    [7] = 'OVERTREDINGEN TEGEN GEZONDHEID EN MOREEL',
    [8] = 'OVERTREDINGEN TEGEN DE OPENBARE VEILIGHEID',
    [9] = 'OVERTREDINGEN MET BETREKKING TOT DE BEDIENING VAN EEN VOERTUIG',
    [10] = 'OVERTREDINGEN DIE HET WELZIJN VAN HET LOKAAL ECOSYSTEEM BEÏNVLOEDEN',
}

Config.PenalCode = {
    [1] = {
        [1] = {title = 'Eenvoudige Aanval', class = 'Misdemeanor', id = 'P.C. 1001', months = 7, fine = 500, color = 'green', description = 'Insert Charge Description Here'},
        [2] = {title = 'Aanval', class = 'Misdemeanor', id = 'P.C. 1002', months = 15, fine = 850, color = 'orange', description = 'Insert Charge Description Here'},
        [3] = {title = 'Zware Mishandeling', class = 'Felony', id = 'P.C. 1003', months = 20, fine = 1250, color = 'orange', description = 'Insert Charge Description Here'},
        [4] = {title = 'Aanval met een dodelijk wapen', class = 'Felony', id = 'P.C. 1004', months = 30, fine = 3750, color = 'red', description = 'Insert Charge Description Here'},
        [5] = {title = 'Onvrijwillige doodslag', class = 'Felony', id = 'P.C. 1005', months = 60, fine = 7500, color = 'red', description = 'Insert Charge Description Here'},
        [6] = {title = 'Doodslag doormiddel van een voertuig', class = 'Felony', id = 'P.C. 1006', months = 75, fine = 7500, color = 'red', description = 'Insert Charge Description Here'},
        [7] = {title = 'Poging tot moord op een burger', class = 'Felony', id = 'P.C. 1007', months = 50, fine = 7500, color = 'red', description = 'Insert Charge Description Here'},
        [8] = {title = 'Tweedegraads moord', class = 'Felony', id = 'P.C. 1008', months = 100, fine = 15000, color = 'red', description = 'Insert Charge Description Here'},
        [9] = {title = 'Medeplichtig aan tweedegraads moord', class = 'Felony', id = 'P.C. 1009', months = 50, fine = 5000, color = 'red', description = 'Insert Charge Description Here'},
        [10] = {title = 'Moord met voorbedachten rade', class = 'Felony', id = 'P.C. 1010', months = 0, fine = 0, color = 'red', description = 'Insert Charge Description Here'},
        [11] = {title = 'Medeplichtig aan eerstegraads moord', class = 'Felony', id = 'P.C. 1011', months = 0, fine = 0, color = 'red', description = 'Insert Charge Description Here'},
        [12] = {title = 'Moord op een ambtenaar of vredesfunctionaris', class = 'Felony', id = 'P.C. 1012', months = 0, fine = 0, color = 'red', description = 'Insert Charge Description Here'},
        [13] = {title = 'Poging tot moord op een ambtenaar of vredesfunctionaris', class = 'Felony', id = 'P.C. 1013', months = 65, fine = 10000, color = 'red', description = 'Insert Charge Description Here'},
        [14] = {title = 'Medeplichtig aan de moord op een ambtenaar of vredesfunctionaris', class = 'Felony', id = 'P.C. 1014', months = 0, fine = 0, color = 'red', description = 'Insert Charge Description Here'},
        [15] = {title = 'Onwettige gevangenisstraf', class = 'Misdemeanor', id = 'P.C. 1015', months = 10, fine = 600, color = 'green', description = 'Insert Charge Description Here'},
        [16] = {title = 'Ontvoering', class = 'Felony', id = 'P.C. 1016', months = 15, fine = 900, color = 'orange', description = 'Insert Charge Description Here'},
        [17] = {title = 'Medeplichtig aan ontvoering', class = 'Felony', id = 'P.C. 1017', months = 7, fine = 450, color = 'orange', description = 'Insert Charge Description Here'},
        [18] = {title = 'Poging tot ontvoering', class = 'Felony', id = 'P.C. 1018', months = 10, fine = 450, color = 'orange', description = 'Insert Charge Description Here'},
        [19] = {title = 'Gijzelneming', class = 'Felony', id = 'P.C. 1019', months = 20, fine = 1200, color = 'orange', description = 'Insert Charge Description Here'},
        [20] = {title = 'Medeplichtig aan gijzelneming', class = 'Felony', id = 'P.C. 1020', months = 10, fine = 600, color = 'orange', description = 'Insert Charge Description Here'},
        [21] = {title = 'Onwettig opsluiting van een ambtenaar of vredesfunctionaris.', class = 'Felony', id = 'P.C. 1021', months = 25, fine = 4000, color = 'orange', description = 'Insert Charge Description Here'},
        [22] = {title = 'Criminele dreigingen', class = 'Misdemeanor', id = 'P.C. 1022', months = 5, fine = 500, color = 'orange', description = 'Insert Charge Description Here'},
        [23] = {title = 'Roekeloos in gevaar brengen', class = 'Misdemeanor', id = 'P.C. 1023', months = 10, fine = 1000, color = 'orange', description = 'Insert Charge Description Here'},
        [24] = {title = 'Bendegerelateerd vuurgevecht', class = 'Felony', id = 'P.C. 1024', months = 30, fine = 2500, color = 'red', description = 'Insert Charge Description Here'},
        [25] = {title = 'Kannibalisme', class = 'Felony', id = 'P.C. 1025', months = 0, fine = 0, color = 'red', description = 'Insert Charge Description Here'},
        [26] = {title = 'Marteling', class = 'Felony', id = 'P.C. 1026', months = 40, fine = 4500, color = 'red', description = 'Insert Charge Description Here'},
        [27] = {title = 'Bedreiging van een burger', class = 'Felony', id = 'P.C. 1026', months = 40, fine = 4500, color = 'red', description = 'Insert Charge Description Here'},
        [28] = {title = 'Bedreiging van een ambtenaar in functie', class = 'Felony', id = 'P.C. 1026', months = 40, fine = 4500, color = 'red', description = 'Insert Charge Description Here'},
    },
    [2] = {
        [1] = {title = 'Diefstal', class = 'Infraction', id = 'P.C. 2001', months = 0, fine = 250, color = 'green', description = 'Insert Charge Description Here'},
        [2] = {title = 'Grote diefstal', class = 'Misdemeanor', id = 'P.C. 2002', months = 10, fine = 600, color = 'green', description = 'Insert Charge Description Here'},
        [3] = {title = 'Autodiefstal A', class = 'Felony', id = 'P.C. 2003', months = 15, fine = 900, color = 'green', description = 'Insert Charge Description Here'},
        [4] = {title = 'Autodiefstal B', class = 'Felony', id = 'P.C. 2004', months = 35, fine = 3500, color = 'green', description = 'Insert Charge Description Here'},
        [5] = {title = 'Autodiefstal', class = 'Felony', id = 'P.C. 2005', months = 30, fine = 2000, color = 'orange', description = 'Insert Charge Description Here'},
        [6] = {title = 'Huis inbraak', class = 'Misdemeanor', id = 'P.C. 2006', months = 10, fine = 500, color = 'green', description = 'Insert Charge Description Here'},
        [7] = {title = 'Roofoverval', class = 'Felony', id = 'P.C. 2007', months = 25, fine = 2000, color = 'green', description = 'Insert Charge Description Here'},
        [8] = {title = 'Medeplichtig aan roofoverval', class = 'Felony', id = 'P.C. 2008', months = 12, fine = 1000, color = 'green', description = 'Insert Charge Description Here'},
        [9] = {title = 'Poging tot beroving', class = 'Felony', id = 'P.C. 2009', months = 20, fine = 1000, color = 'green', description = 'Insert Charge Description Here'},
        [10] = {title = 'Gewapende overval', class = 'Felony', id = 'P.C. 2010', months = 30, fine = 3000, color = 'orange', description = 'Insert Charge Description Here'},
        [11] = {title = 'Medeplichtig aan gewapende overval', class = 'Felony', id = 'P.C. 2011', months = 15, fine = 1500, color = 'orange', description = 'Insert Charge Description Here'},
        [12] = {title = 'Poging tot gewapende overval', class = 'Felony', id = 'P.C. 2012', months = 25, fine = 1500, color = 'orange', description = 'Insert Charge Description Here'},
        [13] = {title = 'Grote diefstal', class = 'Felony', id = 'P.C. 2013', months = 45, fine = 7500, color = 'orange', description = 'Insert Charge Description Here'},
        [14] = {title = 'Weggaan zonder te betalen', class = 'Infraction', id = 'P.C. 2014', months = 0, fine = 500, color = 'green', description = 'Insert Charge Description Here'},
        [15] = {title = 'Bezit van niet-legale valuta', class = 'Misdemeanor', id = 'P.C. 2015', months = 10, fine = 750, color = 'green', description = 'Insert Charge Description Here'},
        [16] = {title = 'Bezit van door de overheid uitgegeven voorwerpen', class = 'Misdemeanor', id = 'P.C. 2016', months = 15, fine = 1000, color = 'green', description = 'Insert Charge Description Here'},
        [17] = {title = 'Bezit van voorwerpen die zijn gebruikt bij het plegen van een misdrijf', class = 'Misdemeanor', id = 'P.C. 2017', months = 10, fine = 500, color = 'green', description = 'Insert Charge Description Here'},
        [18] = {title = 'Verkoop van artikelen die zijn gebruikt bij het plegen van een misdrijf', class = 'Felony', id = 'P.C. 2018', months = 15, fine = 1000, color = 'orange', description = 'Insert Charge Description Here'},
        [19] = {title = 'Diefstal van een vliegtuig', class = 'Felony', id = 'P.C. 2019', months = 20, fine = 1000, color = 'green', description = 'Insert Charge Description Here'},
        [20] = {title = 'Winkel Overval', class = 'Felony', id = 'P.C. 2019', months = 20, fine = 1500, color = 'green', description = 'Insert Charge Description Here'},
        [21] = {title = 'Fleeca Bank Overval', class = 'Felony', id = 'P.C. 2019', months = 25, fine = 10000, color = 'green', description = 'Insert Charge Description Here'},
        [22] = {title = 'Paleto Bank Overval', class = 'Felony', id = 'P.C. 2019', months = 40, fine = 15000, color = 'green', description = 'Insert Charge Description Here'},
        [23] = {title = 'Pacific Bank Overval', class = 'Felony', id = 'P.C. 2019', months = 60, fine = 50000, color = 'green', description = 'Insert Charge Description Here'},
        [24] = {title = 'Jacht overval', class = 'Felony', id = 'P.C. 2019', months = 50, fine = 20000, color = 'green', description = 'Insert Charge Description Here'},
        [24] = {title = 'Banktruck overval', class = 'Felony', id = 'P.C. 2019', months = 50, fine = 7000, color = 'green', description = 'Insert Charge Description Here'},
    },
    [3] = {
        [1] = {title = 'Imitatie', class = 'Misdemeanor', id = 'P.C. 3001', months = 15, fine = 1250, color = 'green', description = 'Insert Charge Description Here'},
        [2] = {title = 'Zich voordoen als een vredesfunctionaris of ambtenaar', class = 'Felony', id = 'P.C. 3002', months = 25, fine = 2750, color = 'green', description = 'Insert Charge Description Here'},
        [3] = {title = 'Zich voordoen als rechter', class = 'Felony', id = 'P.C. 3003', months = 0, fine = 0, color = 'green', description = 'Insert Charge Description Here'},
        [4] = {title = 'In bezit van gestolen identificatie', class = 'Misdemeanor', id = 'P.C. 3004', months = 10, fine = 750, color = 'green', description = 'Insert Charge Description Here'},
        [5] = {title = 'Bezit van gestolen overheidsidentificatie', class = 'Misdemeanor', id = 'P.C. 3005', months = 20, fine = 2000, color = 'green', description = 'Insert Charge Description Here'},
        [6] = {title = 'Afpersing', class = 'Felony', id = 'P.C. 3006', months = 20, fine = 900, color = 'orange', description = 'Insert Charge Description Here'},
        [7] = {title = 'Fraude', class = 'Misdemeanor', id = 'P.C. 3007', months = 10, fine = 450, color = 'green', description = 'Insert Charge Description Here'},
        [8] = {title = 'Namaak', class = 'Misdemeanor', id = 'P.C. 3008', months = 15, fine = 750, color = 'green', description = 'Insert Charge Description Here'},
        [9] = {title = 'Geld witwassen', class = 'Felony', id = 'P.C. 3009', months = 0, fine = 0, color = 'red', description = 'Insert Charge Description Here'},
    },
    [4] = {
        [1] = {title = 'Betreden van een verbode terein', class = 'Misdemeanor', id = 'P.C. 4001', months = 10, fine = 450, color = 'green', description = 'Insert Charge Description Here'},
        [2] = {title = 'Strafbare betredingen van verboden terrein', class = 'Felony', id = 'P.C. 4002', months = 15, fine = 1500, color = 'green', description = 'Insert Charge Description Here'},
        [3] = {title = 'Brandstichting', class = 'Felony', id = 'P.C. 4003', months = 15, fine = 1500, color = 'orange', description = 'Insert Charge Description Here'},
        [4] = {title = 'Vandalisme', class = 'Infraction', id = 'P.C. 4004', months = 0, fine = 300, color = 'green', description = 'Insert Charge Description Here'},
        [5] = {title = 'Vandalisme van overheidseigendom(men)', class = 'Felony', id = 'P.C. 4005', months = 20, fine = 1500, color = 'green', description = 'Insert Charge Description Here'},
        [6] = {title = 'Dumpen van afval', class = 'Infraction', id = 'P.C. 4006', months = 0, fine = 200, color = 'green', description = 'Insert Charge Description Here'},
    },
    [5] = {
        [1] = {title = 'Omkoping van een overheidsfunctionaris', class = 'Felony', id = 'P.C. 5001', months = 20, fine = 3500, color = 'green', description = 'Insert Charge Description Here'},
        [2] = {title = 'Anti-maskerwet', class = 'Infraction', id = 'P.C. 5002', months = 0, fine = 750, color = 'green', description = 'Insert Charge Description Here'},
        [3] = {title = 'Bezit van smokkelwaar in een overheidsgebouw', class = 'Felony', id = 'P.C. 5003', months = 25, fine = 1000, color = 'green', description = 'Insert Charge Description Here'},
        [4] = {title = 'Crimineel bezit van gestolen goederen', class = 'Misdemeanor', id = 'P.C. 5004', months = 10, fine = 500, color = 'green', description = 'Insert Charge Description Here'},
        [5] = {title = 'Ontsnappen', class = 'Felony', id = 'P.C. 5005', months = 10, fine = 450, color = 'green', description = 'Insert Charge Description Here'},
        [6] = {title = 'Ontsnappen uit de gevangenis', class = 'Felony', id = 'P.C. 5006', months = 30, fine = 2500, color = 'orange', description = 'Insert Charge Description Here'},
        [7] = {title = 'Medeplichtig aan ontsnapping uit de gevangenis', class = 'Felony', id = 'P.C. 5007', months = 25, fine = 2000, color = 'orange', description = 'Insert Charge Description Here'},
        [8] = {title = 'Poging tot het ontsnappen uit de gevangenis', class = 'Felony', id = 'P.C. 5008', months = 20, fine = 1500, color = 'orange', description = 'Insert Charge Description Here'},
        [9] = {title = 'Meineed', class = 'Felony', id = 'P.C. 5009', months = 0, fine = 0, color = 'green', description = 'Insert Charge Description Here'},
        [10] = {title = 'Overtreding van een straatverbod', class = 'Felony', id = 'P.C. 5010', months = 20, fine = 2250, color = 'green', description = 'Insert Charge Description Here'},
        [11] = {title = 'Verduistering', class = 'Felony', id = 'P.C. 5011', months = 45, fine = 10000, color = 'green', description = 'Insert Charge Description Here'},
        [12] = {title = 'Onwettige praktijken', class = 'Felony', id = 'P.C. 5012', months = 15, fine = 1500, color = 'orange', description = 'Insert Charge Description Here'},
        [13] = {title = 'Misbruik van noodsystemen', class = 'Infraction', id = 'P.C. 5013', months = 0, fine = 600, color = 'orange', description = 'Insert Charge Description Here'},
        [14] = {title = 'Samenzwering', class = 'Misdemeanor', id = 'P.C. 5014', months = 10, fine = 450, color = 'green', description = 'Insert Charge Description Here'},
        [15] = {title = 'Een gerechtelijk bevel overtreden', class = 'Misdemeanor', id = 'P.C. 5015', months = 0, fine = 0, color = 'orange', description = 'Insert Charge Description Here'},
        [16] = {title = 'Niet verschijnen', class = 'Misdemeanor', id = 'P.C. 5016', months = 0, fine = 0, color = 'orange', description = 'Insert Charge Description Here'},
        [17] = {title = 'Minachting van het hof', class = 'Felony', id = 'P.C. 5017', months = 0, fine = 0, color = 'orange', description = 'Insert Charge Description Here'},
        [18] = {title = 'Verzet bij arrestatie', class = 'Misdemeanor', id = 'P.C. 5018', months = 5, fine = 300, color = 'orange', description = 'Insert Charge Description Here'},
        [19] = {title = 'Smaad aan ambtenaar in functie', class = 'Misdemeanor', id = 'P.C. 5018', months = 5, fine = 300, color = 'orange', description = 'Insert Charge Description Here'},
    },
    [6] = {
        [1] = {title = 'Een vredesofficier ongehoorzamen', class = 'infraction', id = 'P.C. 6001', months = 0, fine = 750, color = 'green', description = 'Insert Charge Description Here'},
        [2] = {title = 'Wanordelijk gedrag', class = 'Infraction', id = 'P.C. 6002', months = 0, fine = 250, color = 'green', description = 'Insert Charge Description Here'},
        [3] = {title = 'De vrede verstoren', class = 'infraction', id = 'P.C. 6003', months = 0, fine = 350, color = 'green', description = 'Insert Charge Description Here'},
        [4] = {title = 'Valse melding', class = 'Misdemeanor', id = 'P.C. 6004', months = 10, fine = 750, color = 'green', description = 'Insert Charge Description Here'},
        [5] = {title = 'Intimidatie', class = 'Misdemeanor', id = 'P.C. 6005', months = 10, fine = 500, color = 'orange', description = 'Insert Charge Description Here'},
        [6] = {title = 'Belemmering van de rechtsgang', class = 'Misdemeanor', id = 'P.C. 6006', months = 10, fine = 500, color = 'green', description = 'Insert Charge Description Here'},
        [7] = {title = 'Belemmering van de rechtsgang tweede graad', class = 'Felony', id = 'P.C. 6007', months = 15, fine = 900, color = 'green', description = 'Insert Charge Description Here'},
        [8] = {title = 'Het aanzetten tot rellen', class = 'Felony', id = 'P.C. 6008', months = 25, fine = 1000, color = 'orange', description = 'Insert Charge Description Here'},
        [9] = {title = 'Rondhangen op overheidseigendommen', class = 'Infraction', id = 'P.C. 6009', months = 0, fine = 500, color = 'green', description = 'Insert Charge Description Here'},
        [10] = {title = 'Sabotage', class = 'Misdemeanor', id = 'P.C. 6010', months = 10, fine = 500, color = 'green', description = 'Insert Charge Description Here'},
        [11] = {title = 'Voertuig sabotage', class = 'Misdemeanor', id = 'P.C. 6011', months = 15, fine = 750, color = 'green', description = 'Insert Charge Description Here'},
        [12] = {title = 'Bewijs manipulatie', class = 'Felony', id = 'P.C. 6012', months = 20, fine = 1000, color = 'green', description = 'Insert Charge Description Here'},
        [13] = {title = 'Sabotage van een getuige', class = 'Felony', id = 'P.C. 6013', months = 0, fine = 0, color = 'green', description = 'Insert Charge Description Here'},
        [14] = {title = 'Identificatie niet verstrekken', class = 'Misdemeanor', id = 'P.C. 6014', months = 15, fine = 1500, color = 'green', description = 'Insert Charge Description Here'},
        [15] = {title = 'Waakzaamheid', class = 'Felony', id = 'P.C. 6015', months = 30, fine = 1500, color = 'orange', description = 'Insert Charge Description Here'},
        [16] = {title = 'Onwettige vergadering', class = 'Misdemeanor', id = 'P.C. 6016', months = 10, fine = 750, color = 'orange', description = 'Insert Charge Description Here'},
        [17] = {title = 'Overheidscorruptie', class = 'Felony', id = 'P.C. 6017', months = 0, fine = 0, color = 'red', description = 'Insert Charge Description Here'},
        [18] = {title = 'Stalking', class = 'Felony', id = 'P.C. 6018', months = 40, fine = 1500, color = 'orange', description = 'Insert Charge Description Here'},
        [19] = {title = 'Helpen en aanzetten tot', class = 'Misdemeanor', id = 'P.C. 6019', months = 15, fine = 450, color = 'orange', description = 'Insert Charge Description Here'},
        [20] = {title = 'Een voortvluchtige herbergen', class = 'Misdemeanor', id = 'P.C. 6020', months = 10, fine = 1000, color = 'green', description = 'Insert Charge Description Here'},
    },
    [7] = {
        [1] = {title = 'Bezit van marihuana', class = 'Mask', id = 'P.C. 7001', months = 5, fine = 250, color = 'green', description = 'Insert Charge Description Here'},
        [2] = {title = 'Bezit van marihuana tweede graad', class = 'Felony', id = 'P.C. 7002', months = 15, fine = 1000, color = 'green', description = 'Insert Charge Description Here'},
        [3] = {title = 'Kweken van marihuana A', class = 'Misdemeanor', id = 'P.C. 7003', months = 10, fine = 750, color = 'green', description = 'Insert Charge Description Here'},
        [4] = {title = 'Kweken van marihuana B', class = 'Felony', id = 'P.C. 7004', months = 30, fine = 1500, color = 'orange', description = 'Insert Charge Description Here'},
        [5] = {title = 'Bezit van marihuana met intentie te dealen', class = 'Felony', id = 'P.C. 7005', months = 30, fine = 3000, color = 'orange', description = 'Insert Charge Description Here'},
        [6] = {title = 'Bezit van cocaïne', class = 'Misdemeanor', id = 'P.C. 7006', months = 7, fine = 500, color = 'green', description = 'Insert Charge Description Here'},
        [7] = {title = 'bezit van cocaïne tweede graad', class = 'Felony', id = 'P.C. 7007', months = 25, fine = 1500, color = 'green', description = 'Insert Charge Description Here'},
        [8] = {title = 'Bezit van cocaïne met intentie te dealen', class = 'Felony', id = 'P.C. 7008', months = 35, fine = 4500, color = 'orange', description = 'Insert Charge Description Here'},
        [9] = {title = 'Bezit van methamfetamine', class = 'Misdemeanor', id = 'P.C. 7009', months = 7, fine = 500, color = 'green', description = 'Insert Charge Description Here'},
        [10] = {title = 'Bezit van methamfetamine tweede graad', class = 'Felony', id = 'P.C. 7010', months = 25, fine = 1500, color = 'green', description = 'Insert Charge Description Here'},
        [11] = {title = 'Bezit van methamfetamine met intentie tot dealen', class = 'Felony', id = 'P.C. 7011', months = 35, fine = 4500, color = 'orange', description = 'Insert Charge Description Here'},
        [12] = {title = 'Bezit van Oxy / Vicodin', class = 'Felony', id = 'P.C. 7012', months = 7, fine = 500, color = 'green', description = 'Insert Charge Description Here'},
        [13] = {title = 'Bezit van Oxy / Vicodin tweede graad', class = 'Felony', id = 'P.C. 7013', months = 25, fine = 1500, color = 'green', description = 'Insert Charge Description Here'},
        [14] = {title = 'Bezit van Oxy / Vicodin met intentie te dealen', class = 'Felony', id = 'P.C. 7014', months = 35, fine = 4500, color = 'orange', description = 'Insert Charge Description Here'},
        [15] = {title = 'Bezit van extacy', class = 'Misdemeanor', id = 'P.C. 7015', months = 7, fine = 500, color = 'green', description = 'Insert Charge Description Here'},
        [16] = {title = 'Bezit van extacy tweede graad', class = 'Felony', id = 'P.C. 7016', months = 25, fine = 1500, color = 'green', description = 'Insert Charge Description Here'},
        [17] = {title = 'Bezit van extacy met intentie te dealen', class = 'Felony', id = 'P.C. 7017', months = 35, fine = 4500, color = 'orange', description = 'Insert Charge Description Here'},
        [18] = {title = 'Bezit van opium', class = 'Misdemeanor', id = 'P.C. 7018', months = 7, fine = 500, color = 'green', description = 'Insert Charge Description Here'},
        [19] = {title = 'Bezit van opium tweede graad', class = 'Felony', id = 'P.C. 7019', months = 25, fine = 1500, color = 'green', description = 'Insert Charge Description Here'},
        [20] = {title = 'Bezit van opium met intentie te dealen', class = 'Felony', id = 'P.C. 7020', months = 35, fine = 4500, color = 'orange', description = 'Insert Charge Description Here'},
        [21] = {title = 'Bezit van adderall', class = 'Misdemeanor', id = 'P.C. 7021', months = 7, fine = 500, color = 'green', description = 'Insert Charge Description Here'},
        [22] = {title = 'Bezit van adderall tweede graad', class = 'Felony', id = 'P.C. 7022', months = 25, fine = 1500, color = 'green', description = 'Insert Charge Description Here'},
        [23] = {title = 'Bezit van adderall met intentie te dealen', class = 'Felony', id = 'P.C. 7023', months = 35, fine = 4500, color = 'orange', description = 'Insert Charge Description Here'},
        [24] = {title = 'Bezit van Xanax', class = 'Misdemeanor', id = 'P.C. 7024', months = 7, fine = 500, color = 'green', description = 'Insert Charge Description Here'},
        [25] = {title = 'Bezit van Xanax tweede graad', class = 'Felony', id = 'P.C. 7025', months = 25, fine = 1500, color = 'green', description = 'Insert Charge Description Here'},
        [26] = {title = 'Bezit van Xanax met intentie te dealen', class = 'Felony', id = 'P.C. 7026', months = 35, fine = 4500, color = 'orange', description = 'Insert Charge Description Here'},
        [27] = {title = 'Bezit van paddos', class = 'Misdemeanor', id = 'P.C. 7027', months = 7, fine = 500, color = 'green', description = 'Insert Charge Description Here'},
        [28] = {title = 'Bezit van paddos tweede graad', class = 'Felony', id = 'P.C. 7028', months = 25, fine = 1500, color = 'green', description = 'Insert Charge Description Here'},
        [29] = {title = 'Bezit van paddos met de intentie te dealen', class = 'Felony', id = 'P.C. 7029', months = 35, fine = 4500, color = 'orange', description = 'Insert Charge Description Here'},
        [30] = {title = 'Bezit van Lean', class = 'Misdemeanor', id = 'P.C. 7030', months = 7, fine = 500, color = 'green', description = 'Insert Charge Description Here'},
        [31] = {title = 'Bezit van Lean tweede graad', class = 'Felony', id = 'P.C. 7031', months = 25, fine = 1500, color = 'green', description = 'Insert Charge Description Here'},
        [32] = {title = 'Bezit van Lean met intentie te dealen', class = 'Felony', id = 'P.C. 7032', months = 35, fine = 4500, color = 'orange', description = 'Insert Charge Description Here'},
        [33] = {title = 'Verkoop van een gereguleerde substantie', class = 'Misdemeanor', id = 'P.C. 7033', months = 10, fine = 1000, color = 'green', description = 'Insert Charge Description Here'},
        [34] = {title = 'Drugshandel', class = 'Felony', id = 'P.C. 7034', months = 0, fine = 0, color = 'red', description = 'Insert Charge Description Here'},
        [35] = {title = 'Desecration of a Human Corpse', class = 'Felony', id = 'P.C. 7035', months = 20, fine = 1500, color = 'orange', description = 'Insert Charge Description Here'},
        [36] = {title = 'Ontheiliging van een menselijk lijk', class = 'Infraction', id = 'P.C. 7036', months = 0, fine = 500, color = 'green', description = 'Insert Charge Description Here'},
        [37] = {title = 'Openbaar dronkenschap', class = 'Misdemeanor', id = 'P.C. 7037', months = 10, fine = 750, color = 'green', description = 'Insert Charge Description Here'},
    },
    [8] = {
        [1] = {title = 'Crimineel bezit van wapenklasse A', class = 'Felony', id = 'P.C. 8001', months = 10, fine = 500, color = 'green', description = 'Insert Charge Description Here'},
        [2] = {title = 'Crimineel bezit van wapenklasse B', class = 'Felony', id = 'P.C. 8002', months = 15, fine = 1000, color = 'green', description = 'Insert Charge Description Here'},
        [3] = {title = 'Crimineel bezit van wapenklasse C', class = 'Felony', id = 'P.C. 8003', months = 30, fine = 3500, color = 'green', description = 'Insert Charge Description Here'},
        [4] = {title = 'Crimineel bezit van wapenklasse D', class = 'Felony', id = 'P.C. 8004', months = 25, fine = 1500, color = 'green', description = 'Insert Charge Description Here'},
        [5] = {title = 'Criminele verkoop van wapenklasse A', class = 'Felony', id = 'P.C. 8005', months = 15, fine = 1000, color = 'orange', description = 'Insert Charge Description Here'},
        [6] = {title = 'Criminele verkoop van wapenklasse B', class = 'Felony', id = 'P.C. 8006', months = 20, fine = 2000, color = 'orange', description = 'Insert Charge Description Here'},
        [7] = {title = 'Criminele verkoop van wapenklasse C', class = 'Felony', id = 'P.C. 8007', months = 35, fine = 7000, color = 'orange', description = 'Insert Charge Description Here'},
        [8] = {title = 'Criminele verkoop van wapenklasse D', class = 'Felony', id = 'P.C. 8008', months = 30, fine = 3000, color = 'orange', description = 'Insert Charge Description Here'},
        [9] = {title = 'Crimineel gebruik van een wapen', class = 'Misdemeanor', id = 'P.C. 8009', months = 10, fine = 450, color = 'orange', description = 'Insert Charge Description Here'},
        [10] = {title = 'Het bezit van illegale vuurwapenaanpassingen', class = 'Misdemeanor', id = 'P.C. 8010', months = 10, fine = 300, color = 'green', description = 'Insert Charge Description Here'},
        [11] = {title = 'Wapenhandel', class = 'Felony', id = 'P.C. 8011', months = 0, fine = 0, color = 'red', description = 'Insert Charge Description Here'},
        [12] = {title = 'Zwaaien met een wapen', class = 'Misdemeanor', id = 'P.C. 8012', months = 15, fine = 500, color = 'orange', description = 'Insert Charge Description Here'},
        [13] = {title = 'Opstand', class = 'Felony', id = 'P.C. 8013', months = 0, fine = 0, color = 'red', description = 'Insert Charge Description Here'},
        [14] = {title = 'Vliegen naar beperkt luchtruim', class = 'Felony', id = 'P.C. 8014', months = 20, fine = 1500, color = 'green', description = 'Insert Charge Description Here'},
        [15] = {title = 'Jaywalking', class = 'Infraction', id = 'P.C. 8015', months = 0, fine = 150, color = 'green', description = 'Insert Charge Description Here'},
        [16] = {title = 'Crimineel gebruik van explosieven', class = 'Felony', id = 'P.C. 8016', months = 30, fine = 2500, color = 'orange', description = 'Insert Charge Description Here'},
    },
    [9] = {
        [1] = {title = 'Rijden onder invloed', class = 'Misdemeanor', id = 'P.C. 9001', months = 5, fine = 300, color = 'green', description = 'Insert Charge Description Here'},
        [2] = {title = 'Ontsnappen', class = 'Misdemeanor', id = 'P.C. 9002', months = 5, fine = 400, color = 'green', description = 'Insert Charge Description Here'},
        [3] = {title = 'Roekeloos ontsnappen', class = 'Felony', id = 'P.C. 9003', months = 10, fine = 800, color = 'orange', description = 'Insert Charge Description Here'},
        [4] = {title = 'Niet toegeven aan noodvoertuig', class = 'Infraction', id = 'P.C. 9004', months = 0, fine = 600, color = 'green', description = 'Insert Charge Description Here'},
        [5] = {title = 'Het niet gehoorzamen aan het verkeersregelapparaat', class = 'Infraction', id = 'P.C. 9005', months = 0, fine = 150, color = 'green', description = 'Insert Charge Description Here'},
        [6] = {title = 'Niet-functioneel voertuig', class = 'Infraction', id = 'P.C. 9006', months = 0, fine = 75, color = 'green', description = 'Insert Charge Description Here'},
        [7] = {title = 'Nalatig rijden', class = 'Infraction', id = 'P.C. 9007', months = 0, fine = 300, color = 'green', description = 'Insert Charge Description Here'},
        [8] = {title = 'Roekeloos rijden', class = 'Misdemeanor', id = 'P.C. 9008', months = 10, fine = 750, color = 'orange', description = 'Insert Charge Description Here'},
        [9] = {title = 'Negeren van een rood verkeerslicht', class = 'Infraction', id = 'P.C. 9009', months = 0, fine = 300, color = 'green', description = 'Insert Charge Description Here'},
        [10] = {title = 'Derde graads snelheidsovertreding', class = 'Infraction', id = 'P.C. 9009', months = 0, fine = 225, color = 'green', description = 'Insert Charge Description Here'},
        [11] = {title = 'Tweede graads snelheidsovertreding', class = 'Infraction', id = 'P.C. 9010', months = 0, fine = 450, color = 'green', description = 'Insert Charge Description Here'},
        [12] = {title = 'Eerste graads snelheidsovertreding', class = 'Infraction', id = 'P.C. 9011', months = 0, fine = 750, color = 'green', description = 'Insert Charge Description Here'},
        [13] = {title = 'Gebruik van een voertuig zonder vergunning', class = 'Infraction', id = 'P.C. 9012', months = 0, fine = 500, color = 'green', description = 'Insert Charge Description Here'},
        [14] = {title = 'Illegale U-bocht', class = 'Infraction', id = 'P.C. 9013', months = 0, fine = 75, color = 'green', description = 'Insert Charge Description Here'},
        [15] = {title = 'Illegaal inhaalmanoeuvre', class = 'Infraction', id = 'P.C. 9014', months = 0, fine = 300, color = 'green', description = 'Insert Charge Description Here'},
        [16] = {title = 'Het niet houden aan de rijstrook', class = 'Infraction', id = 'P.C. 9015', months = 0, fine = 300, color = 'green', description = 'Insert Charge Description Here'},
        [17] = {title = 'Illegale afslag', class = 'Infraction', id = 'P.C. 9016', months = 0, fine = 150, color = 'green', description = 'Insert Charge Description Here'},
        [18] = {title = 'Niet stoppen', class = 'Infraction', id = 'P.C. 9017', months = 0, fine = 600, color = 'green', description = 'Insert Charge Description Here'},
        [19] = {title = 'Onbevoegd Parkeren', class = 'Infraction', id = 'P.C. 9018', months = 0, fine = 300, color = 'green', description = 'Insert Charge Description Here'},
        [20] = {title = 'Vluchtmisdrijf', class = 'Misdemeanor', id = 'P.C. 9019', months = 10, fine = 500, color = 'green', description = 'Insert Charge Description Here'},
        [21] = {title = 'Rijden zonder koplampen en pinkers', class = 'Infraction', id = 'P.C. 9020', months = 0, fine = 300, color = 'green', description = 'Insert Charge Description Here'},
        [22] = {title = 'Straatracen', class = 'Felony', id = 'P.C. 9021', months = 15, fine = 1500, color = 'green', description = 'Insert Charge Description Here'},
        [23] = {title = 'Vliegtuig besturen zonder wettige licentie', class = 'Felony', id = 'P.C. 9022', months = 20, fine = 1500, color = 'orange', description = 'Insert Charge Description Here'},
        [24] = {title = 'Onwettig gebruik van een motorvoertuig', class = 'Misdemeanor', id = 'P.C. 9023', months = 10, fine = 750, color = 'green', description = 'Insert Charge Description Here'},
        [25] = {title = 'Gerechtelijke takeling', class = 'Misdemeanor', id = 'P.C. 9023', months = 0, fine = 250, color = 'green', description = 'Insert Charge Description Here'},
    },
    [10] = {
        [1] = {title = 'Jagen in een verboden gebieden', class = 'Infraction', id = 'P.C. 10001', months = 0, fine = 450, color = 'green', description = 'Insert Charge Description Here'},
        [2] = {title = 'Jagen zonder vergunning', class = 'Infraction', id = 'P.C. 10002', months = 0, fine = 450, color = 'green', description = 'Insert Charge Description Here'},
        [3] = {title = 'Dierenmishandeling', class = 'Misdemeanor', id = 'P.C. 10003', months = 10, fine = 450, color = 'green', description = 'Insert Charge Description Here'},
        [4] = {title = 'Jagen met een niet-jachtwapen', class = 'Misdemeanor', id = 'P.C. 10004', months = 10, fine = 750, color = 'green', description = 'Insert Charge Description Here'},
        [5] = {title = 'Jagen buiten de jachturen', class = 'Infraction', id = 'P.C. 10005', months = 0, fine = 750, color = 'green', description = 'Insert Charge Description Here'},
        [6] = {title = 'Overbejaging', class = 'Misdemeanor', id = 'P.C. 10006', months = 10, fine = 1000, color = 'green', description = 'Insert Charge Description Here'},
        [7] = {title = 'Stropen', class = 'Felony', id = 'P.C. 10007', months = 20, fine = 1250, color = 'red', description = 'Insert Charge Description Here'},
    }
}

Config.AllowedJobs = {}
for index, value in pairs(Config.PoliceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.AmbulanceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.DojJobs) do
    Config.AllowedJobs[index] = value
end

Config.ColorNames = {
    [0] = "Metallic Black",
    [1] = "Metallic Graphite Black",
    [2] = "Metallic Black Steel",
    [3] = "Metallic Dark Silver",
    [4] = "Metallic Silver",
    [5] = "Metallic Blue Silver",
    [6] = "Metallic Steel Gray",
    [7] = "Metallic Shadow Silver",
    [8] = "Metallic Stone Silver",
    [9] = "Metallic Midnight Silver",
    [10] = "Metallic Gun Metal",
    [11] = "Metallic Anthracite Grey",
    [12] = "Matte Black",
    [13] = "Matte Gray",
    [14] = "Matte Light Grey",
    [15] = "Util Black",
    [16] = "Util Black Poly",
    [17] = "Util Dark silver",
    [18] = "Util Silver",
    [19] = "Util Gun Metal",
    [20] = "Util Shadow Silver",
    [21] = "Worn Black",
    [22] = "Worn Graphite",
    [23] = "Worn Silver Grey",
    [24] = "Worn Silver",
    [25] = "Worn Blue Silver",
    [26] = "Worn Shadow Silver",
    [27] = "Metallic Red",
    [28] = "Metallic Torino Red",
    [29] = "Metallic Formula Red",
    [30] = "Metallic Blaze Red",
    [31] = "Metallic Graceful Red",
    [32] = "Metallic Garnet Red",
    [33] = "Metallic Desert Red",
    [34] = "Metallic Cabernet Red",
    [35] = "Metallic Candy Red",
    [36] = "Metallic Sunrise Orange",
    [37] = "Metallic Classic Gold",
    [38] = "Metallic Orange",
    [39] = "Matte Red",
    [40] = "Matte Dark Red",
    [41] = "Matte Orange",
    [42] = "Matte Yellow",
    [43] = "Util Red",
    [44] = "Util Bright Red",
    [45] = "Util Garnet Red",
    [46] = "Worn Red",
    [47] = "Worn Golden Red",
    [48] = "Worn Dark Red",
    [49] = "Metallic Dark Green",
    [50] = "Metallic Racing Green",
    [51] = "Metallic Sea Green",
    [52] = "Metallic Olive Green",
    [53] = "Metallic Green",
    [54] = "Metallic Gasoline Blue Green",
    [55] = "Matte Lime Green",
    [56] = "Util Dark Green",
    [57] = "Util Green",
    [58] = "Worn Dark Green",
    [59] = "Worn Green",
    [60] = "Worn Sea Wash",
    [61] = "Metallic Midnight Blue",
    [62] = "Metallic Dark Blue",
    [63] = "Metallic Saxony Blue",
    [64] = "Metallic Blue",
    [65] = "Metallic Mariner Blue",
    [66] = "Metallic Harbor Blue",
    [67] = "Metallic Diamond Blue",
    [68] = "Metallic Surf Blue",
    [69] = "Metallic Nautical Blue",
    [70] = "Metallic Bright Blue",
    [71] = "Metallic Purple Blue",
    [72] = "Metallic Spinnaker Blue",
    [73] = "Metallic Ultra Blue",
    [74] = "Metallic Bright Blue",
    [75] = "Util Dark Blue",
    [76] = "Util Midnight Blue",
    [77] = "Util Blue",
    [78] = "Util Sea Foam Blue",
    [79] = "Uil Lightning blue",
    [80] = "Util Maui Blue Poly",
    [81] = "Util Bright Blue",
    [82] = "Matte Dark Blue",
    [83] = "Matte Blue",
    [84] = "Matte Midnight Blue",
    [85] = "Worn Dark blue",
    [86] = "Worn Blue",
    [87] = "Worn Light blue",
    [88] = "Metallic Taxi Yellow",
    [89] = "Metallic Race Yellow",
    [90] = "Metallic Bronze",
    [91] = "Metallic Yellow Bird",
    [92] = "Metallic Lime",
    [93] = "Metallic Champagne",
    [94] = "Metallic Pueblo Beige",
    [95] = "Metallic Dark Ivory",
    [96] = "Metallic Choco Brown",
    [97] = "Metallic Golden Brown",
    [98] = "Metallic Light Brown",
    [99] = "Metallic Straw Beige",
    [100] = "Metallic Moss Brown",
    [101] = "Metallic Biston Brown",
    [102] = "Metallic Beechwood",
    [103] = "Metallic Dark Beechwood",
    [104] = "Metallic Choco Orange",
    [105] = "Metallic Beach Sand",
    [106] = "Metallic Sun Bleeched Sand",
    [107] = "Metallic Cream",
    [108] = "Util Brown",
    [109] = "Util Medium Brown",
    [110] = "Util Light Brown",
    [111] = "Metallic White",
    [112] = "Metallic Frost White",
    [113] = "Worn Honey Beige",
    [114] = "Worn Brown",
    [115] = "Worn Dark Brown",
    [116] = "Worn straw beige",
    [117] = "Brushed Steel",
    [118] = "Brushed Black steel",
    [119] = "Brushed Aluminium",
    [120] = "Chrome",
    [121] = "Worn Off White",
    [122] = "Util Off White",
    [123] = "Worn Orange",
    [124] = "Worn Light Orange",
    [125] = "Metallic Securicor Green",
    [126] = "Worn Taxi Yellow",
    [127] = "police car blue",
    [128] = "Matte Green",
    [129] = "Matte Brown",
    [130] = "Worn Orange",
    [131] = "Matte White",
    [132] = "Worn White",
    [133] = "Worn Olive Army Green",
    [134] = "Pure White",
    [135] = "Hot Pink",
    [136] = "Salmon pink",
    [137] = "Metallic Vermillion Pink",
    [138] = "Orange",
    [139] = "Green",
    [140] = "Blue",
    [141] = "Mettalic Black Blue",
    [142] = "Metallic Black Purple",
    [143] = "Metallic Black Red",
    [144] = "Hunter Green",
    [145] = "Metallic Purple",
    [146] = "Metaillic V Dark Blue",
    [147] = "MODSHOP BLACK1",
    [148] = "Matte Purple",
    [149] = "Matte Dark Purple",
    [150] = "Metallic Lava Red",
    [151] = "Matte Forest Green",
    [152] = "Matte Olive Drab",
    [153] = "Matte Desert Brown",
    [154] = "Matte Desert Tan",
    [155] = "Matte Foilage Green",
    [156] = "DEFAULT ALLOY COLOR",
    [157] = "Epsilon Blue",
    [158] = "Unknown",
}

Config.ColorInformation = {
    [0] = "black",
    [1] = "black",
    [2] = "black",
    [3] = "darksilver",
    [4] = "silver",
    [5] = "bluesilver",
    [6] = "silver",
    [7] = "darksilver",
    [8] = "silver",
    [9] = "bluesilver",
    [10] = "darksilver",
    [11] = "darksilver",
    [12] = "matteblack",
    [13] = "gray",
    [14] = "lightgray",
    [15] = "black",
    [16] = "black",
    [17] = "darksilver",
    [18] = "silver",
    [19] = "utilgunmetal",
    [20] = "silver",
    [21] = "black",
    [22] = "black",
    [23] = "darksilver",
    [24] = "silver",
    [25] = "bluesilver",
    [26] = "darksilver",
    [27] = "red",
    [28] = "torinored",
    [29] = "formulared",
    [30] = "blazered",
    [31] = "gracefulred",
    [32] = "garnetred",
    [33] = "desertred",
    [34] = "cabernetred",
    [35] = "candyred",
    [36] = "orange",
    [37] = "gold",
    [38] = "orange",
    [39] = "red",
    [40] = "mattedarkred",
    [41] = "orange",
    [42] = "matteyellow",
    [43] = "red",
    [44] = "brightred",
    [45] = "garnetred",
    [46] = "red",
    [47] = "red",
    [48] = "darkred",
    [49] = "darkgreen",
    [50] = "racingreen",
    [51] = "seagreen",
    [52] = "olivegreen",
    [53] = "green",
    [54] = "gasolinebluegreen",
    [55] = "mattelimegreen",
    [56] = "darkgreen",
    [57] = "green",
    [58] = "darkgreen",
    [59] = "green",
    [60] = "seawash",
    [61] = "midnightblue",
    [62] = "darkblue",
    [63] = "saxonyblue",
    [64] = "blue",
    [65] = "blue",
    [66] = "blue",
    [67] = "diamondblue",
    [68] = "blue",
    [69] = "blue",
    [70] = "brightblue",
    [71] = "purpleblue",
    [72] = "blue",
    [73] = "ultrablue",
    [74] = "brightblue",
    [75] = "darkblue",
    [76] = "midnightblue",
    [77] = "blue",
    [78] = "blue",
    [79] = "lightningblue",
    [80] = "blue",
    [81] = "brightblue",
    [82] = "mattedarkblue",
    [83] = "matteblue",
    [84] = "matteblue",
    [85] = "darkblue",
    [86] = "blue",
    [87] = "lightningblue",
    [88] = "yellow",
    [89] = "yellow",
    [90] = "bronze",
    [91] = "yellow",
    [92] = "lime",
    [93] = "champagne",
    [94] = "beige",
    [95] = "darkivory",
    [96] = "brown",
    [97] = "brown",
    [98] = "lightbrown",
    [99] = "beige",
    [100] = "brown",
    [101] = "brown",
    [102] = "beechwood",
    [103] = "beechwood",
    [104] = "chocoorange",
    [105] = "yellow",
    [106] = "yellow",
    [107] = "cream",
    [108] = "brown",
    [109] = "brown",
    [110] = "brown",
    [111] = "white",
    [112] = "white",
    [113] = "beige",
    [114] = "brown",
    [115] = "brown",
    [116] = "beige",
    [117] = "steel",
    [118] = "blacksteel",
    [119] = "aluminium",
    [120] = "chrome",
    [121] = "wornwhite",
    [122] = "offwhite",
    [123] = "orange",
    [124] = "lightorange",
    [125] = "green",
    [126] = "yellow",
    [127] = "blue",
    [128] = "green",
    [129] = "brown",
    [130] = "orange",
    [131] = "white",
    [132] = "white",
    [133] = "darkgreen",
    [134] = "white",
    [135] = "pink",
    [136] = "pink",
    [137] = "pink",
    [138] = "orange",
    [139] = "green",
    [140] = "blue",
    [141] = "blackblue",
    [142] = "blackpurple",
    [143] = "blackred",
    [144] = "darkgreen",
    [145] = "purple",
    [146] = "darkblue",
    [147] = "black",
    [148] = "purple",
    [149] = "darkpurple",
    [150] = "red",
    [151] = "darkgreen",
    [152] = "olivedrab",
    [153] = "brown",
    [154] = "tan",
    [155] = "green",
    [156] = "silver",
    [157] = "blue",
    [158] = "black",
}

Config.ClassList = {
    [0] = "Compact",
    [1] = "Sedan",
    [2] = "SUV",
    [3] = "Coupe",
    [4] = "Muscle",
    [5] = "Sport Classic",
    [6] = "Sport",
    [7] = "Super",
    [8] = "Motorbike",
    [9] = "Off-Road",
    [10] = "Industrial",
    [11] = "Utility",
    [12] = "Van",
    [13] = "Bike",
    [14] = "Boat",
    [15] = "Helicopter",
    [16] = "Plane",
    [17] = "Service",
    [18] = "Emergency",
    [19] = "Military",
    [20] = "Commercial",
    [21] = "Train"
}

function GetJobType(job)
	if Config.PoliceJobs[job] then
		return 'police'
	elseif Config.AmbulanceJobs[job] then
		return 'ambulance'
	elseif Config.DojJobs[job] then
		return 'doj'
	else
		return nil
	end
end